---

- name: CAPTURE DATE AND CREATE DIRECTORY
  hosts: localhost

  tasks:

    - name: Capture Date
      command: date +"%Y-%m-%d"
      register: time
      changed_when: false
      delegate_to: localhost

    - name: Create Directory
      file:
        path: ~/network-automation/backup/{{time.stdout}}
        state: directory
  run_once: yes

- name: BACKUP ARISTA SWITCHES
  hosts: eos
  gather_facts: false
  connection: network_cli

  tasks:
    - name: ARISTA SWITCH CONFIG
      eos_command:
        commands: show run
      register: output

    - name: SAVE ARISTA SWITCH CONFIG
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "~/network-automation/backup/{{hostvars.localhost.time.stdout}}/show_run_{{ inventory_hostname }}.txt"

- name: SAVE AND UPLOAD TO GIT 
  hosts: localhost

  tasks:

    - name: git commands
      shell: |
        git add .
        git commit -m "Device Backup on {{hostvars.localhost.time.start}} "
        git push
      args:
        chdir: ~/network-automation/backup/{{hostvars.localhost.time.stdout}}
      delegate_to: localhost
      run_once: yes
