---

- name: CAPTURE DATE AND CREATE DIRECTORY
  hosts: localhost
  
  tasks:

    - name: Capture Date
      command: date +"%Y-%m-%d"
      register: time
      changed_when: false
      delegate_to: localhost

    - name: Create Directory
      file:
        path: ~/network-automation/backup/{{time.stdout}}
        state: directory
  run_once: yes
