---
nautobot_host: "http://{{ lookup('env', 'NB_HOST') }}:8000"
nautobot_token: "{{ lookup('env', 'NB_TOKEN') }}"

# "fbf4caacbd265dfc88aa430be6c31650a84179a7"
devices:
  - name: "clab-Arista-2s-3l-spine1"
    site: "Connecticut"
    device_role: "Switch"
    device_type: "ceos"
    platform: "EOS"
  - name: "clab-Arista-2s-3l-spine2"
    site: "Connecticut"
    device_role: "Switch"
    device_type: "ceos"
    platform: "EOS"
  - name: "clab-Arista-2s-3l-leaf1"
    site: "Connecticut"
    device_role: "Switch"
    device_type: "ceos"
    platform: "EOS"
  - name: "clab-Arista-2s-3l-leaf2"
    site: "Connecticut"
    device_role: "Switch"
    device_type: "ceos"
    platform: "EOS"
  - name: "clab-Arista-2s-3l-leaf3"
    site: "Connecticut"
    device_role: "Switch"
    device_type: "ceos"
    platform: "EOS"